version: "3"

services:
  ghost:
    image: ghost:3.25-alpine
    container_name: ghost_app
    ports:
      - "2368:2368"
    environment:
      url: ${APP_HOST_URL}
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${APP_DB_USER}
      database__connection__password: ${APP_DB_PASSWORD}
      database__connection__database: ${APP_DATABASE}
    volumes:
      - "./ghost_content/:/var/lib/ghost/content/"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: database
    ports:
      - "3306:3306"
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8",
        "--collation-server=utf8_general_ci",
      ]
    volumes:
      - "./db_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${APP_DATABASE}
      MYSQL_ROOT_PASSWORD: ${APP_DB_ROOT_PASSWORD}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
